Написал функцию sum.
js-tasks-ru/js-20200622_ivza pull request #1
Opened 2020-06-28 23:52 UTC by IvanZabaznov

2020-06-28 23:58 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Первая задача
+ should return sum of numbers
```

Добавляю преподавателя (@dosandk) для код-ревью, посмотрим что он скажет :)

2020-06-29 13:55 UTC, jsru commented
@dosandk ping :)

2020-06-29 17:34 UTC, jsru commented
@dosandk ping :)

2020-06-30 10:10 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    arrSort.sort((a, b) => a.localeCompare(b, [], {caseFirst: 'upper'}));
строка 11 дублирует строку 13 за исключением порядка аргументов `a` и `b` - это нужно исправить

2020-06-30 10:11 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +  for (let [key, value] of Object.entries(obj)) {
`let [key, value]` -> `const [key, value]`

2020-06-30 10:11 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +  for (let [key, value] of Object.entries(obj)) {
`let [key, value]` -> `const [key, value]`

2020-06-30 10:12 UTC, dosandk requested changes
Пожалуйста посмотрите комментарии и внесите изменения

2020-06-30 11:01 UTC, jsru commented
@dosandk ping :)

2020-07-01 11:42 UTC, dosandk approved these changes
решения принимаются good 👍

2020-07-01 11:42 UTC, merged